name: moniplan
description: A new Flutter project.
publish_to: 'none'
version: 1.0.6+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  moniplan_core:
    path: moniplan_core

  moniplan_uikit:
    path: moniplan_uikit

  # UI
  draggable_scrollbar: 0.1.0
  permission_handler: 11.3.1
  sliver_tools: 0.2.12
  share_plus: 9.0.0
  file_picker: 8.0.6

  syncfusion_flutter_charts: 26.1.35

  # Data management
  flutter_bloc: 8.1.6

  # Data
  intl: 0.19.0
  firebase_core: 3.1.0

  # Persistent
  shared_preferences: 2.2.3
  drift_db_viewer: 2.1.0
  sqlite3_flutter_libs: 0.5.23
  path_provider: 2.1.3
  path: 1.9.0


dev_dependencies:
  flutter_lints: 4.0.0

  # Test
  bloc_test: 9.1.7
  flutter_test:
    sdk: flutter

  # Codegen
  build_runner: 2.4.11
  freezed: 2.5.2
  json_serializable: 6.8.0

  # Tools
  packo: 0.5.1


flutter:
  uses-material-design: true
  fonts:
    - family: SfProText
      fonts:
        - asset: fonts/SF-Pro-Text-Regular.otf
    - family: SfProDisplay
      fonts:
        - asset: fonts/SF-Pro-Display-Regular.otf
        - asset: fonts/SF-Pro-Display-Bold.otf
