name: moniplan
description: A new Flutter project.
publish_to: 'none'
version: 1.6.0+16

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  moniplan_core:
    path: moniplan_core

  moniplan_uikit:
    path: moniplan_uikit

  # UI
  responsive_framework: ^1.5.1
  draggable_scrollbar: 0.1.0
  permission_handler: 11.3.1
  share_plus: 10.1.2
  file_picker: 8.1.4
  stack_trace: 1.11.1
  syncfusion_flutter_charts: 27.2.3
  dynamic_color: 1.7.0
  receive_sharing_intent:
    git: https://github.com/nogipx/receive_sharing_intent

  # Sliver
  sliver_tools: 0.2.12
  super_sliver_list: 0.4.1
  sticky_headers: 0.3.0+2

  # Data management
  flutter_bloc: 8.1.6

  # Data
  logging: any
  intl: 0.19.0
  package_info_plus: 8.1.2

  # Persistent
  shared_preferences: ^2.3.3
  drift_db_viewer: 2.1.0
  sqlite3_flutter_libs: ^0.5.26
  path_provider: ^2.1.5
  path: 1.9.0

  # Analytics
  posthog_flutter: 4.7.0

dev_dependencies:
  flutter_lints: 4.0.0

  # Test
  bloc_test: 9.1.7
  flutter_test:
    sdk: flutter

  # Codegen
  build_runner: 2.4.11
  freezed: 2.5.2
  json_serializable: 6.8.0

  # Tools
  packo: 0.5.1


flutter:
  uses-material-design: true
  fonts:
    - family: TTNeoris
      fonts:
        - asset: fonts/TT-Neoris-Variable.ttf
  assets:
    - 'assets/'
