name: moniplan
description: A new Flutter project.
publish_to: 'none'
version: 1.0.6+6

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  sticky_infinite_list: ^4.0.0
  modal_bottom_sheet: ^2.0.0
  intl: ^0.17.0
  money2: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter_slidable: ^1.1.0
  responsive_framework: ^0.1.2

  # State
  dartx: ^1.0.0
  bloc: ^8.0.1
  flutter_bloc: ^8.0.0
  easy_debounce: ^2.0.1
  get_it: ^7.2.0

  # Storage
  hive: ^2.0.4
  hive_flutter: ^1.0.0

  # Entities Tools
  uuid: ^3.0.4
  equatable: ^2.0.0
  copy_with_extension: ^2.0.0
  json_annotation: ^4.0.0
  freezed_annotation: ^1.1.0

  flutter_riverpod: ^1.0.3
  riverpod: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  freezed: ^1.1.0

  json_serializable: ^6.1.1
  hive_generator: ^1.1.1
  bloc_test: ^9.0.1
  # test: ^1.16.8
  build_runner: ^2.1.5
  copy_with_extension_gen: ^2.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: SfProText
      fonts:
        - asset: fonts/SF-Pro-Text-Regular.otf
    - family: SfProDisplay
      fonts:
        - asset: fonts/SF-Pro-Display-Regular.otf
        - asset: fonts/SF-Pro-Display-Bold.otf
