name: moniplan
description: A new Flutter project.
publish_to: 'none'
version: 1.0.6+6

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  money2: ^3.0.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.0
  draggable_scrollbar: ^0.1.0

  fast_immutable_collections: ^7.4.1
  syncfusion_flutter_charts: ^20.4.42

  moniplan_core:
    path: packages/moniplan_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.1.1
  bloc_test: ^9.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: SfProText
      fonts:
        - asset: fonts/SF-Pro-Text-Regular.otf
    - family: SfProDisplay
      fonts:
        - asset: fonts/SF-Pro-Display-Regular.otf
        - asset: fonts/SF-Pro-Display-Bold.otf
