name: moniplan
description: A new Flutter project.
publish_to: 'none'
version: 1.0.6+6

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  sticky_infinite_list: ^4.0.0
  money2: ^3.0.0
  navigation_manager: ^1.2.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.0
  uuid: ^3.0.4
  equatable: ^2.0.0
  json_annotation: ^4.0.0
  freezed_annotation: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  freezed: ^1.1.0
  json_serializable: ^6.1.1
  bloc_test: ^9.0.1
  build_runner: ^2.1.5

flutter:
  uses-material-design: true
  fonts:
    - family: SfProText
      fonts:
        - asset: fonts/SF-Pro-Text-Regular.otf
    - family: SfProDisplay
      fonts:
        - asset: fonts/SF-Pro-Display-Regular.otf
        - asset: fonts/SF-Pro-Display-Bold.otf
