name: moniplan
description: A new Flutter project.
publish_to: 'none'
version: 1.0.5+5

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  sticky_infinite_list: ^4.0.0
  modal_bottom_sheet: ^2.0.0
  intl: ^0.17.0
  money2: ^2.0.2
  cupertino_icons: ^1.0.2
  flutter_slidable: ^0.6.0
  responsive_framework: ^0.1.2

  # State
  dartx: ^0.7.1
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  easy_debounce: ^2.0.1

  # Storage
  hive: ^2.0.4
  hive_flutter: ^1.0.0

  # Entities Tools
  uuid: ^3.0.4
  equatable: ^2.0.0
  copy_with_extension: ^2.0.0
  json_annotation: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^4.0.0
  hive_generator: ^1.1.0
  bloc_test: ^8.0.0
  # test: ^1.16.8
  build_runner: ^1.12.2
  copy_with_extension_gen: ^2.0.1

flutter:
  uses-material-design: true