name: moniplan
description: A new Flutter project.
publish_to: 'none'
version: 1.1.0+10

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  moniplan_core:
    path: moniplan_core

  moniplan_uikit:
    path: moniplan_uikit

  # UI
  responsive_framework: 1.4.0
  draggable_scrollbar: 0.1.0
  permission_handler: 11.3.1
  sliver_tools: 0.2.12
  share_plus: 10.0.2
  file_picker: 8.1.2
  scrollable_positioned_list: 0.3.8
  stack_trace: 1.11.1
  syncfusion_flutter_charts: 26.1.35
  receive_sharing_intent:
    git: https://github.com/nogipx/receive_sharing_intent

  # Data management
  flutter_bloc: 8.1.6

  # Data
  intl: 0.19.0
  firebase_core: 3.1.0

  # Persistent
  shared_preferences: 2.2.3
  drift_db_viewer: 2.1.0
  sqlite3_flutter_libs: 0.5.23
  path_provider: 2.1.3
  path: 1.9.0


dev_dependencies:
  flutter_lints: 4.0.0

  # Test
  bloc_test: 9.1.7
  flutter_test:
    sdk: flutter

  # Codegen
  build_runner: 2.4.11
  freezed: 2.5.2
  json_serializable: 6.8.0

  # Tools
  packo: 0.5.1


flutter:
  uses-material-design: true
  fonts:
    - family: TTNeoris
      fonts:
        - asset: fonts/TT-Neoris-Variable.ttf
