version = 1

[[annotations]]
path = [
    "moniplan_app/lib/**",
    "moniplan_core/lib/**",
    "moniplan_domain/lib/**",
    "moniplan_uikit/lib/**",
]
SPDX-FileCopyrightText = "2025 Karim nogipx Mamatkazin <nogipx@gmail.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"