name: moniplan_domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  money2: 5.0.1
  uuid: 4.3.3
  equatable: 2.0.5
  json_annotation: 4.9.0
  freezed_annotation: 2.4.1
  intl: 0.19.0
  encrypt: 5.0.3
  feature_core: 2.0.0

dev_dependencies:
  lints: 3.0.0
  test: 1.25.2
  build_runner: 2.4.9
  freezed: 2.5.0
  json_serializable: 6.8.0
  keys_generator: ^1.1.1
