name: moniplan_domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Stable
  feature_core: 2.0.0
  intl: 0.19.0
  json_annotation: 4.9.0
  freezed_annotation: 2.4.4
  uuid: 4.5.1
  equatable: 2.0.7
  encrypt: 5.0.3

  # Not stable
  money2: 5.4.6

dev_dependencies:
  lints: 5.0.0
  test: 1.25.12
  build_runner: 2.4.13
  freezed: 2.5.7
  json_serializable: 6.9.0
  keys_generator: 1.1.1
