// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTrKb627x09cFadLv9Gl6wpo5rC3-fg6I',
    appId: '1:848767447335:web:e2e72657078d009c7cb902',
    messagingSenderId: '848767447335',
    projectId: 'moniplan-nogipx',
    authDomain: 'moniplan-nogipx.firebaseapp.com',
    storageBucket: 'moniplan-nogipx.appspot.com',
    measurementId: 'G-DRSKVBDYEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqgrJTuNIKdiKWvX_7qbhtw-zNxue4I3Q',
    appId: '1:848767447335:android:89bbe076d4338d307cb902',
    messagingSenderId: '848767447335',
    projectId: 'moniplan-nogipx',
    storageBucket: 'moniplan-nogipx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiI3i5cPOO3FGhTTdt9e8L1f6JGlPEEGc',
    appId: '1:848767447335:ios:dfbd58d8acd5ae537cb902',
    messagingSenderId: '848767447335',
    projectId: 'moniplan-nogipx',
    storageBucket: 'moniplan-nogipx.appspot.com',
    iosBundleId: 'dev.nogipx.moniplan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiI3i5cPOO3FGhTTdt9e8L1f6JGlPEEGc',
    appId: '1:848767447335:ios:dfbd58d8acd5ae537cb902',
    messagingSenderId: '848767447335',
    projectId: 'moniplan-nogipx',
    storageBucket: 'moniplan-nogipx.appspot.com',
    iosBundleId: 'dev.nogipx.moniplan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTrKb627x09cFadLv9Gl6wpo5rC3-fg6I',
    appId: '1:848767447335:web:b2a98854759990c57cb902',
    messagingSenderId: '848767447335',
    projectId: 'moniplan-nogipx',
    authDomain: 'moniplan-nogipx.firebaseapp.com',
    storageBucket: 'moniplan-nogipx.appspot.com',
    measurementId: 'G-QFZMERHXT8',
  );
}
