name: moniplan_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  moniplan_domain:
    path: ../moniplan_domain

  drift: 2.20.2

  bloc: 8.1.4
  bloc_concurrency: 0.2.5

  json_annotation: 4.9.0
  freezed_annotation: 2.4.1

dev_dependencies:
  # Code Quality
  bloc_test: 9.1.7
  lints: 3.0.0
  test: 1.25.2

  # Codegen
  build_runner: 2.4.9
  freezed: 2.5.0
  json_serializable: 6.8.0
  drift_dev: 2.20.3

