name: moniplan_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  intl: ^0.17.0
  money2: ^3.0.0

  bloc: ^8.0.3
  bloc_concurrency: ^0.2.0

  fast_immutable_collections: ^7.4.1
  uuid: ^3.0.4
  equatable: ^2.0.5
  json_annotation: ^4.0.0
  freezed_annotation: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.2
  bloc_test: ^9.0.1
