name: moniplan_app
description: A new Flutter project.
publish_to: 'none'
version: 2.0.1+51

environment:
  sdk: '>=3.9.0 <4.0.0'

dependency_overrides:
  pointycastle: ^3.6.2
#  rpc_dart:
#    path: /Users/nogipx/nogipx_vault/projects/libraries/rpc_dart/packages/rpc_dart
#  rpc_dart_transports:
#    path: /Users/nogipx/nogipx_vault/projects/libraries/rpc_dart/packages/rpc_dart_transports

dependencies:
  flutter:
    sdk: flutter

  # nogipx-libs
  licensify: ^3.1.0
  paseto_dart: ^1.0.1
  data_manage: ^3.0.2
  rpc_dart: ^2.3.0
  rpc_dart_transports: ^1.2.0

  # Modules
  moniplan_uikit:
    path: ../moniplan_uikit
  monishare:
    path: ../monishare

  freezed_annotation: ^3.1.0
  uuid: ^4.5.1
  json_annotation: ^4.9.0
  collection: ^1.18.0

  # UI
  responsive_framework: ^1.5.1
  draggable_scrollbar: 0.1.0
  permission_handler: ^12.0.1
  share_plus: ^12.0.0
  file_picker: ^10.3.3
  dynamic_color: ^1.8.1
#  receive_sharing_intent:
#    git: https://github.com/nogipx/receive_sharing_intent
  oktoast: 3.4.0
  fl_chart: ^1.1.1

  # Sliver
  sliver_tools: 0.2.12
  super_sliver_list: 0.4.1
  sticky_headers: 0.3.0+2

  # Data management
  flutter_bloc: ^9.0.0

  # Data
  cross_file: ^0.3.4+2
  logging: any
  get_it: ^8.2.0
  intl: ^0.20.2
  package_info_plus: ^9.0.0
  device_info_plus: ^12.1.0
  encrypt: 5.0.3
  crypto: ^3.0.6
  equatable: ^2.0.7
  expressions: ^0.2.5+2
  stack_trace: ^1.12.1
  flutter_secure_storage: ^10.0.0-beta.4
  envied: ^1.1.1

  # Persistent
  shared_preferences: ^2.3.3
  drift_db_viewer: 2.1.0
  sqlite3_flutter_libs: ^0.5.39
  path_provider: ^2.1.5
  path: ^1.9.1

  # Persistence
  drift: ^2.28.1

  # State
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0

dev_dependencies:
  flutter_lints: ^6.0.0

  # Test
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter

  # Codegen
  build_runner: ^2.4.15
  freezed: ^3.2.3
  json_serializable: ^6.9.0
  drift_dev: ^2.22.1
  envied_generator: ^1.1.1


flutter:
  uses-material-design: true
  fonts:
    - family: TTNeoris
      fonts:
        - asset: fonts/TT-Neoris-Variable.ttf
  assets:
    - 'assets/'

flutter_intl:
  enabled: true
  arb_dir: lib/i18n/arb
  output_dir: lib/i18n/generated
  use_deferred_loading: false
