name: moniplan_app
description: A new Flutter project.
publish_to: 'none'
version: 1.9.0+19
resolution: workspace

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Modules
  moniplan_core:
  moniplan_uikit:

  # UI
  responsive_framework: ^1.5.1
  draggable_scrollbar: 0.1.0
  permission_handler: 11.3.1
  share_plus: ^10.1.3
  file_picker: 8.1.4
  dynamic_color: 1.7.0
  receive_sharing_intent:
    git: https://github.com/nogipx/receive_sharing_intent
  oktoast: 3.4.0
  fl_chart: ^0.70.0

  # Sliver
  sliver_tools: 0.2.12
  super_sliver_list: 0.4.1
  sticky_headers: 0.3.0+2

  # Data management
  flutter_bloc: 8.1.6

  # Data
  logging: any
  get_it: 8.0.3
  intl: ^0.19.0
  package_info_plus: 8.1.2
  device_info_plus: 11.2.0

  # Persistent
  shared_preferences: ^2.3.3
  drift_db_viewer: 2.1.0
  sqlite3_flutter_libs: ^0.5.26
  path_provider: ^2.1.5
  path: 1.9.0

  # Analytics
  posthog_flutter: ^4.8.0

dev_dependencies:
  flutter_lints: ^5.0.0

  # Test
  bloc_test: 9.1.7
  flutter_test:
    sdk: flutter

  # Codegen
  build_runner: 2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0

  # Tools
  packo: 0.5.1


flutter:
  uses-material-design: true
  fonts:
    - family: TTNeoris
      fonts:
        - asset: fonts/TT-Neoris-Variable.ttf
  assets:
    - 'assets/'

flutter_intl:
  enabled: true
  arb_dir: lib/i18n/arb
  output_dir: lib/i18n/generated
  use_deferred_loading: false
